### ISSUE TITLE
Clarification Request on Address Standardization and 'amt' Parameter Consistency in bnb-48 Inscription Standard

### ISSUE THREAD

**Issue by BigWinner721** [48Club/bnb-48-inscription#9]
Hello,

I have a few questions regarding the bnb-48 inscription standard, especially concerning the handling of addresses and the consistency of the 'amt' parameter in different operations.

**Standardization of 'from' and 'to' Addresses in Operations:**

In operations like 'transfer', the current implementation allows transactions to be sent to one's own address, while the JSON object specifies another person's address. What would be the implications if the 'to' address is changed to another person's address? Is it reasonable to have self-transfers in the JSON object?

**Consistency of the 'amt' Parameter:**

There seems to be a discrepancy in how the 'amt' parameter is treated in different operations. For instance, in 'fans' transfers, 'amt' includes decimals, which appears inconsistent with its usage in the 'mint' operation. This inconsistency is a bit confusing.

Could you please clarify these points? Your insights would be greatly appreciated.

Thank you!

**Comment by 48ClubIan** [comment]
> Hello,
> 
> I have a few questions regarding the bnb-48 inscription standard, especially concerning the handling of addresses and the consistency of the 'amt' parameter in different operations.
> 
> **Standardization of 'from' and 'to' Addresses in Operations:**
> 
> In operations like 'transfer', the current implementation allows transactions to be sent to one's own address, while the JSON object specifies another person's address. What would be the implications if the 'to' address is changed to another person's address? Is it reasonable to have self-transfers in the JSON object?
> 
> **Consistency of the 'amt' Parameter:**
> 
> There seems to be a discrepancy in how the 'amt' parameter is treated in different operations. For instance, in 'fans' transfers, 'amt' includes decimals, which appears inconsistent with its usage in the 'mint' operation. This inconsistency is a bit confusing.
> 
> Could you please clarify these points? Your insights would be greatly appreciated.
> 
> Thank you!

1. According to the spec, the "to" address of the tx only matters in mint operation as the receiver. In all other asset moving cases,  "to" is a mandatory parameter in dataload. It doesn't make any difference anyway to do self-transfer.
2. $fans is a special case, and the only case, simply because it's a pioneer trial before the spec was even established.

**Comment by BigWinner721** [comment]
> > Hello,
> > I have a few questions regarding the bnb-48 inscription standard, especially concerning the handling of addresses and the consistency of the 'amt' parameter in different operations.
> > **Standardization of 'from' and 'to' Addresses in Operations:**
> > In operations like 'transfer', the current implementation allows transactions to be sent to one's own address, while the JSON object specifies another person's address. What would be the implications if the 'to' address is changed to another person's address? Is it reasonable to have self-transfers in the JSON object?
> > **Consistency of the 'amt' Parameter:**
> > There seems to be a discrepancy in how the 'amt' parameter is treated in different operations. For instance, in 'fans' transfers, 'amt' includes decimals, which appears inconsistent with its usage in the 'mint' operation. This inconsistency is a bit confusing.
> > Could you please clarify these points? Your insights would be greatly appreciated.
> > Thank you!
> 
> 1. According to the spec, the "to" address of the tx only matters in mint operation as the receiver. In all other asset moving cases,  "to" is a mandatory parameter in dataload. It doesn't make any difference anyway to do self-transfer.
> 2. $fans is a special case, and the only case, simply because it's a pioneer trial before the spec was even established.

I suggest that when transferring to other addresses, the recipient's address should be used, as relying solely on self-transfers can lead to high dependency on indexers, preventing the recipient from receiving immediate confirmation on the blockchain.

**Comment by 48ClubIan** [comment]
It might be less confusing this way, but sometimes we just can not do like this e.g. in bulk operation there are multiple receivers.

For the latter consideration, it won't be an performance issue as far as the indexer focuses on the call data as they are supposed to.

**Comment by BigWinner721** [comment]
> It might be less confusing this way, but sometimes we just can not do like this e.g. in bulk operation there are multiple receivers.
> 
> For the latter consideration, it won't be an performance issue as far as the indexer focuses on the call data as they are supposed to.

Regarding the first point, I understand that you aim to prevent double-spending, but if a person sends multiple self-transfer transactions simultaneously, similar issues still exist. Thank you for your response! Indexers are crucial, and I wonder if there's an opportunity for me to access the indexer's API, as I am planning to develop some applications.

**Comment by 48ClubIan** [comment]
> > It might be less confusing this way, but sometimes we just can not do like this e.g. in bulk operation there are multiple receivers.
> > For the latter consideration, it won't be an performance issue as far as the indexer focuses on the call data as they are supposed to.
> 
> Regarding the first point, I understand that you aim to prevent double-spending, but if a person sends multiple self-transfer transactions simultaneously, similar issues still exist. Thank you for your response! Indexers are crucial, and I wonder if there's an opportunity for me to access the indexer's API, as I am planning to develop some applications.

They can still send multiple transactions regardless we allow or not to use different to address in valid ops.

You can F12, actually ...

**Comment by BigWinner721** [comment]
> > > It might be less confusing this way, but sometimes we just can not do like this e.g. in bulk operation there are multiple receivers.
> > > For the latter consideration, it won't be an performance issue as far as the indexer focuses on the call data as they are supposed to.
> > 
> > 
> > Regarding the first point, I understand that you aim to prevent double-spending, but if a person sends multiple self-transfer transactions simultaneously, similar issues still exist. Thank you for your response! Indexers are crucial, and I wonder if there's an opportunity for me to access the indexer's API, as I am planning to develop some applications.
> 
> They can still send multiple transactions regardless we allow or not to use different to address in valid ops.
> 
> You can F12, actually ...

.....
